### ISSUE TITLE
Unable to connect

### ISSUE THREAD

**Issue by tgoetheyn** [zealic/dockerfiles#2]
Hi,

Thanks for you work in de DST docker container.
I started the container and set port forwarding on my router on port 10999

the problem is that the server is 't reachable.
i checked on https://dstservers.jacklul.com/ and the server is visible, but i get a "Server might be unreachable."

i updated the server version from within the container, but without succes.
Do you have the same problem?

**Comment by zealic** [comment]
Server program need update.
I was updated container, you can try it again.
