### ISSUE TITLE
Is DST_SERVER_VERSION only used to trigger auto build?

### ISSUE THREAD

**Issue by stackia** [zealic/dockerfiles#3]
Does it actually affect the server version if I rebuild this Dockerfile with another value?

**Comment by zealic** [comment]
YES!

**Comment by thasmo** [comment]
@zealic, interesting. Where is `DST_SERVER_VERSION` used? Is it used by `steamcmd`? Is `DST_SERVER_VERSION` documented somewhere?

**Comment by zealic** [comment]
@thasmo 
Not anywhere, just for mark build version.
